insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("VENKATESH","0","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("TIRUMALESH","0","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("NARENDRA","0","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("EQBAL","12","WEEKLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("MOHINUDDIN","12.5","WEEKLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("VIJAY SODA","12.5","WEEKLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("RAILWAY STATION","18","WEEKLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("VIJAY ","15","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("MAHADEV ","15","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("NAGARAJ","15","MONTHLY","","","");
insert into hawker(hawker_name,hawker_discount,billing_cycle,phone_number,alternate_phone) values ("MALLESH","0","MONTHLY","","","");
