insert into item(item_name,description,Default_Price,item_life,returnable) values("Super hit (Te);","","12","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("FHM","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Circket today (E);","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tantra jothya (H);","","55","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business India","","25","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business sphere","","25","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Retail India shop","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Auto car","","125","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Osha Vachna","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("A.B.N","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Yuva","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Parent & Child","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Data Quest","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("TechNlogy Review","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("M ","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Home Revivew","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Exibit","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Dare","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Asian Photography","","75","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("All sports","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tinkle","","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("P.C.Quest","","125","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("electronics for you","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("business ecoNmy","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("computer active","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Mother & Baby","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("auto india","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Idea home","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("greh lakshmi(h);","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Inside outside","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("osha world","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Suppandi","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Smart Photography","","125","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("stuff India","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("What car","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Car India","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Gladrags","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Legal era","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Linux for you","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Perfect Women","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Verve","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("What Wi Fi","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("sports wear International","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Images Retail","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("The  Man","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("S.U.M","","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Osho Vachana (K);","K","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("M.Y.O.D","E","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("T.S.I (K);","K","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("T.S.I (E);","E","20","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Cine Mirchi(Te);","TE","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook (H);","H","15","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook(E);","E","30","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook Business","e","30","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Art attack","E","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business Today","E","30","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Purusharige Maathra","K","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sparda Jagathu","K","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Star Of Bangalore","K","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Employment News","E","8","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Nai Duniya (U);","U","15","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chandamama (E);","e","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Junior Chandamama","E","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Star Dust (E);","e","75","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Prathiyogita Kiran (E);","E","55","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Hai Bangalore","k","14","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Motoring","E","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Swapna","TE","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Vasudha","TE","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kumudum Repoter","ta","9","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kumudum Health","Ta","15","fortnight","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kumudum Theernathi","ta","15","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("T3","K","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sanjeevni","K","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("India Today (E);","E","30","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sparda Spoorthi","K","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Vipula","Te","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chatura","Te","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kungumam","Ta","10","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Roopatara","k","16","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business World","E","15","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Udyoga Jothi","K","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("India Today (TA);","TA","15","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Men's Health","E","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Reader's digest","E","60","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("India Today(Te);","Te","15","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Entrepreneur","E","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tell Me Why","E","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sparda Chithra","K","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Police News","K","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Karmaveer","K","12","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook Travellar","E","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Careers 360","E","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GhrahaShobha (H);","H","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Champak (H);","H","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Champak (H CD);","H CD","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chouti Duniya (U);","U","5","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Alive","E","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GhrahaShobha (TA);","Ta","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Annadatha (TE);","te","11","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("JuNir Viktan","Ta","11","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Magic Pot","E","15","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Nasheman","U","4","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook Money","E","30","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Frontline","e","25","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GhrahaShobha (K);","K","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Digit","E","150","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Gowri Lankesh","K","14","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("santosham","Te","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sitar","Te","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("G.k. Today","e","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Wisdom","E","12","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Meri Seheli","H","25","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Gubbachhi Gudu","K","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Competition Vision","E","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kalkandu","Ta","9","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Mangala","K","10","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Balamangala","k","6","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Gilivindu","k","10","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Jyothisha Sudha","k","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business & EcoNmy","E","25","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Lankeash","k","14","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sparda Vijetha","k","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Taranga","k","12","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Vijaya Next","k","6","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Ananda Viktana","Ta","19","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sports star","e","12","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Swathi","Te","10","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Agni","k","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Aragni","k","15","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Seni tara","Te","15","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chiranjali","Te","12","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Outlook (E);","E","30","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sampadyam","Ta","15","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Fast Track","Ta","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Navaraga Sangama","K","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Arogya Anuraga","k","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Suman Souraba","H","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Women's era","E","35","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GhrahaShobha (Malm);","M","30","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Champak (E);","e","20","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Champak (E CD);","E Cd","30","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Pakeeza Anchal","U","35","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Khatan mashirq","U","35","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("maNrama Mangala","M","5","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Dalal Street","E","65","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Bindiya (E);","k","25","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Money Life","e","30","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Teacher","k","13","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Thunthuru","k","6","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Good House Keeping","e","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Manasa","k","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Anadatha (K);","k","12","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("competition 360","e","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("People","e","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Butti","K","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Rani","ta","7","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Job news","K","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Aval Viktan","Ta","20","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Duniya","K","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Circket (K);","K","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("New City Police news","k","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Vioar-e-Hind","U","20","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Femina","E","50","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Huma","U","40","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Science reporter","e","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Gokulam","E","15","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Current Affairs","E","30","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Navya","Te","10","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("4 P's","e","25","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Human factor","e","25","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sara silila","H","6","fortnight","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chithara","K","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Business India","e","20","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Beauty & Style","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Osho World (E);","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Film fare(E);","","50","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Balamangala ChitraKathe","","5","fortnight","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("S.S.L.C. Winner","","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kasturi","","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Udyoga Varthe","","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Police Mirror","","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Reporter (K);","","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Kumdum Bakthi","","17","fortnight","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("sikshana Udyoga Mahete","","10","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("udyoga Jagathu","","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("JUNIOR VIKTANA","","11","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("BANKING SERVICE CHRONICLE","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("DEVELOPER IQ","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("AAYURVEDA SANJEEVINI","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("C.S.R","","75","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("MASHRIQI DULHAN","","35","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("PREMA Samrajya","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("civil service chronicle","","70","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("crime news","","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("crime stories","","10","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chitra","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("G&G","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("L.Guide","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("MaNrama Arogayam","","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("CV","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("PCM Childrens Magazine","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tinkle Digest","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("JYOTHISHA TARANGA (k);","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("DHARMIKA VANI","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("PYSCOLOGY","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("TUNTURU","","6","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Spy","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Hamsaraga","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tara Darshini","","15","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Star week ","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("G.K.","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Juraim ","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("My Mobile","","75","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sakhi (H);","","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Future Samachar","","35","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Tilismati Duniya","","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Shama","","35","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Competation Wizard","","60","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Mehandi","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Circket Bharathi (H);","","35","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Chanakya ","","45","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Sobhagaya deep","","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Banking Awareness","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Modern Astrology","","40","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("prathiyogita Darapan (H);","","60","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("prathiyogita Darapan (E);","","60","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("overdrive","","125","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("Money Today","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("SALAR (U);","","5","W","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("TUSHARA","","10","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("BETTER PHOTOGRAPHY","","150","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("TIBBI DIGEST","","20","M","N");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GANDA HENDATHI","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("arogya spurthi","","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("SENI GANDA","","20","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("AUTO CAR INDIA","","125","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("BIKE INDIA","","80","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("DIABETES HEALTH","","50","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("VANITHA (H);","","15","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("BETTER INTERIORS","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("SPORTS STAR","","12","W","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("BALA BHARATHI","","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("VANITHA (M);","","25","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("GEO","","100","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("STUDY PLANNER","","30","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("SARITHA","","25","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("SALIL (Te);","","5","fortnight","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("ANDRABHOOMI ","","10","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("DIWAM","","51","M","Y");
insert into item(item_name,description,Default_Price,item_life,returnable) values("CHIP","","150","M","N");
