DROP TABLE IF EXISTS Alert_Association;
DROP TABLE IF EXISTS Alert_Config;
DROP TABLE IF EXISTS Alert;
DROP TABLE IF EXISTS Group_Items;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Alert_Type;