DROP TABLE IF EXISTS Item_Vendor;

DROP TABLE IF EXISTS PT_Details;

DROP TABLE IF EXISTS ST_Details;

DROP TABLE IF EXISTS Payment_History_Procurement;

DROP TABLE IF EXISTS Billing_Procurement;

DROP TABLE IF EXISTS Billing_Sales;

DROP TABLE IF EXISTS Sales_Transaction;

DROP TABLE IF EXISTS Stock;

DROP TABLE IF EXISTS Payment_History_Sales;

DROP TABLE IF EXISTS Procurement_Transaction;

DROP TABLE IF EXISTS Vendor;

DROP TABLE IF EXISTS Item;

DROP TABLE IF EXISTS Hawker;


